bottega_mikrotik_admin_password: ENC[AES256_GCM,data:Dht/dK/womK4geFOj4dk/1WLLZ6pSNklXv4cvaI0muw=,iv:g44eMK5imuGDv9F70E9+kb+Wmk3VJqXM6ynVh1miT+E=,tag:C2yWlEbaOROnbMsY1LwxQA==,type:str]
bottega_cloudflare_dns_api_token: ENC[AES256_GCM,data:hE3WAhnlDWZZW2oOQR4wnYTYWZNCNf9vUum8sJEHKxvzaslf0ILqq9twvX7qV9OYgS8GdW4=,iv:3ONMn4NPeay8wFKKf6uV+LeulCBtBbd+ASJ+lbgnOXI=,tag:FMdV+qgZhD0MCTx8OXvVgA==,type:str]
bottega_cloudflare_zone_id: ENC[AES256_GCM,data:fg/NeWcD75PYkxtHxTq1EVOt3XUS3HE9KjXzWaJED80=,iv:pokf6zwRUqklrB1ofZA0xH8B1y9m90XDqejghy1uso8=,tag:t3EMJeM9SUHC1Lm5szgvuA==,type:str]
sops:
    age:
        - recipient: age1rxyzhqxykdrx9rt504dxjd0hch3aysxs0dzrsnfadc4ur59q537s7w873e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHc0xreDlvSm0xS0dzN01E
            amZjaVlkSWdDSC9Ndzh2SUtRc1RhU1VlY3pjCjMrOC9uRXpEQllndkVmUmdJT3NW
            aWpSR1VhcHFPZnpWKzlUb3dIc2RrWWcKLS0tIHhIb0ZkYjJsbkhaTzZmSnk1R1VF
            TjBBOVhtZXlOZDVjNmFLL2NUejExYkUKRPlBfE3BdUkIrReZMU6skrWtUw9eSRSs
            tocaoUj1p1oMF34MBX+BcPW9zjvgYE5bW9bQFWP1aKtmHHsO16QSNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-26T22:12:45Z"
    mac: ENC[AES256_GCM,data:QiNWyNVRjXGAePAuMTF7ftrbCsFrocTvnrgT2H/QitRFr54e43PHK/ApdMiGidQukrZc6iE5WrBayTv3l4nsO2+sY+pUvq0xGlktcD5PNngr/5MqZcGVs4/0x9qVa5ht+oEpHKwqA1qiJfTshsK0MSmtHFeJO5dB9+5dfB9FgXU=,iv:V9v3o2S3AoXUEgl1+7/KaVUZUPHzMlhfACP0ojNL7Gs=,tag:43gUA7AJpKChUxQ+Wjd+FA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
