bottega_mikrotik_admin_password: ENC[AES256_GCM,data:Dht/dK/womK4geFOj4dk/1WLLZ6pSNklXv4cvaI0muw=,iv:g44eMK5imuGDv9F70E9+kb+Wmk3VJqXM6ynVh1miT+E=,tag:C2yWlEbaOROnbMsY1LwxQA==,type:str]
sops:
    age:
        - recipient: age1rxyzhqxykdrx9rt504dxjd0hch3aysxs0dzrsnfadc4ur59q537s7w873e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHc0xreDlvSm0xS0dzN01E
            amZjaVlkSWdDSC9Ndzh2SUtRc1RhU1VlY3pjCjMrOC9uRXpEQllndkVmUmdJT3NW
            aWpSR1VhcHFPZnpWKzlUb3dIc2RrWWcKLS0tIHhIb0ZkYjJsbkhaTzZmSnk1R1VF
            TjBBOVhtZXlOZDVjNmFLL2NUejExYkUKRPlBfE3BdUkIrReZMU6skrWtUw9eSRSs
            tocaoUj1p1oMF34MBX+BcPW9zjvgYE5bW9bQFWP1aKtmHHsO16QSNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-26T09:26:21Z"
    mac: ENC[AES256_GCM,data:Rsc0SVx369VaSZK/XtNWT9+rWihTIXbZfi8Jmb4lMSuz9YL96vAR/OAQ8c7s7oEWNjLjmekCDLxDLxLvUYFgWKiK7dlYiVsB+CnxVUjmxD/ABNWjnu25r1eBs6R4CScKccF8e38Ga/JkXAGXY/5KmO0XGvADZB0ufSPWxxe8hIs=,iv:4IVKnf/syCJwcRZJsnnnvKo1IZ+zHUZ9HCqqeQ++0zY=,tag:OLhKvHUp7YAqVP1Z2r2T6A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
