apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: internal-allowlist
  namespace: traefik
spec:
  ipAllowList:
    sourceRange:
      - 10.10.0.0/24   # Management VLAN
      - 10.20.0.0/24   # Trusted LAN
      - 10.30.0.0/24   # Kubernetes VLAN
      - 10.100.0.0/24  # WireGuard (VPS + road warrior clients)
      - 192.168.88.0/24 # MikroTik default bridge
