proxmox_api_token: ENC[AES256_GCM,data:YwkXQcbPNYCd80JZeIXBVzLzSkkYswF/1MvhzD6tfvoFVB0t0msLOVem8ckzzTy0JU14/fCEljOz4g==,iv:v6K/TUlorGm/gisUtjDMBwmEO2P+Me3+SasGK2xg9m0=,tag:m4JPYIJto9iWBrUccpSmyA==,type:str]
sops:
    age:
        - recipient: age18nas3jz5knygax063tjeek855fx69jc3ycn9kzn9qxpdnhe3957s8dz9ky
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwYi9zZk5KZk5wdXFlNUNn
            QjNPL0VidXFTZDhSdU1WYmpiZVlFUzhtK21zCkJvREpadjdsQms3M1B6UzRiWGhj
            SERqeG1uWEY2bEY0UjdCVmR0dTRzaUEKLS0tIGZZdWdNZjRYUnlPMlFYTlJweW13
            L3hyeWZMY2NqeGFyODFYMG9jOTU0ck0KXiOpEQLoxoGam6DBrXUbjeaTeieV893q
            3WrV1oHnjHXnJSy6L08cGvvN0EuNARG+7uBf6pbKROXVErlWIkeVaw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1rxyzhqxykdrx9rt504dxjd0hch3aysxs0dzrsnfadc4ur59q537s7w873e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmVHVwanM0QS80SEtuM2wx
            WnQ1Y0RYemZpSW4zNHpRbU9CK2N6QmVqSWo0CnprRHhTckh3L0d3VHMyVkJ5K0hI
            OUk3UmxqOFRrcnc3Tmh3SlBzRDBvVGMKLS0tIDk4TGJuS3l2UWxobWgwTGR2RS95
            UE9FMExXbk9UUzBtcllaL0FMaStpME0KUYFzS0PSDyYEAtenhAOWkFeAmRDmzPLW
            zPAiFQBdZtvOKtKluB/W56FFL5pPruYd1om06nhDa1t47JQWchyM8g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-17T09:02:48Z"
    mac: ENC[AES256_GCM,data:/cz+pkPk6E0jCY8kakr1+KO6R0r+s+AkBvf3qkRs9N3Jt2hcI38ouCnX0ti2HZn/WLFuf2/oqOkhFJ8oOf0qzhGL+9Kp0WHSneu69Ey+Mxezel84banOJ1u9o7H/JaAcPZJxH5xlpjp2VakG0BWx6KlS7NsM3LjmRltxNjZ4FDM=,iv:LJUkF7/Rz+0K0I0MfExOatb+UbL74zQh2kPcSaSedDc=,tag:QtNUP5hlZPirhgNzKHjM1g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.1
