proxmox_api_token: ENC[AES256_GCM,data:C3RbG8iDQLsVuOxbR0sJf2yzF2XHgNY/BSxgnuGKm1j76WJq0wF59VeGlZdBPhGJF4PO4BpZL8Gdvg==,iv:v6K/TUlorGm/gisUtjDMBwmEO2P+Me3+SasGK2xg9m0=,tag:aKXWW4pvIj3nWdvgDL8VGg==,type:str]
sops:
    age:
        - recipient: age18nas3jz5knygax063tjeek855fx69jc3ycn9kzn9qxpdnhe3957s8dz9ky
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByZFRjU2VoRHp3TElBUlF2
            azRHeW1maDE5U1BHWTI1NDhTeFZPYzVwYmtJCkZiL0J4TlpPZm93Y0Y5cG9qaVNE
            WU9uMmV4Wkk0UmxnZWc3QksreUFWZEEKLS0tIExVRkxmNVpULzUrWHoycS9YdHR2
            K3EyaTJnT0ZrbmsxVzh4aDY5Y1hNYzgKqt8DjDPiHip1THbvozaNKABf/nYUjqjr
            TpkbNvoXXXBhxMOfo8bVnggbb3eTV4wJayHbtCfsgzPhATMWaNBdjw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-17T08:09:44Z"
    mac: ENC[AES256_GCM,data:g5zKrUXVZ/KAPEwLrvU3EVzjwCbS+J/ZCgu0Lp/Xfxi6bsnE5d0QjCyjIA/CxYgqOSFnouW3KgElZje2SKM2NjkIHN0i1UF3X9ZtCA8+mLIg2uu/9vOUtRd6fsYqao097c9+f4LHkl2Uc2cpBBNUnTfUV39wKqZu83TgVDP7iqw=,iv:QQ8VS9CYlL/Qucb8Xz2l7OB0FSav7EarLA5U4G6Idm4=,tag:7cvoQvxkq+kbHJrEH9N2zQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.1
