proxmox_api_token: ENC[AES256_GCM,data:cffQ4Bxhl2j+LeNSTn4iR689oFjWAV3h04QMmZ4MuBQR16W1Vz0nL8uvQmohqn79tBZwzPKk3hQF0Q==,iv:v6K/TUlorGm/gisUtjDMBwmEO2P+Me3+SasGK2xg9m0=,tag:HzZqOjyBX8NhmF2fshIt8g==,type:str]
sops:
    age:
        - recipient: age18nas3jz5knygax063tjeek855fx69jc3ycn9kzn9qxpdnhe3957s8dz9ky
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiNE92ZEg5anJaUlhoY3Yz
            S1pLNEd3WTExQ2w0UmpMbXVaZlk1SzBZOG1nCldPeFlBVm9mWCt2bnpnT0NML202
            SzlIUm5KNWZNNWNTVFJMYW9Zdys3bVkKLS0tIDNwdDdQeEZKV2RZdkJtNlBlTzRX
            UGt6VVc1Yng4Qjdod3RpYjVYYURkL2cK96E3QCcLn07XcmXaJFDpLvnCwxVq5nev
            QXico5jQwnyJMnO2ZWVVFDERNJzlvfZ/yd9mtbgBhDSZ8Qz+c/TVQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-17T08:42:48Z"
    mac: ENC[AES256_GCM,data:nkD50NktK3XIRBPUSweLWO4pzbf95b7Wh6ydbGXc1bIjjNtwGuumdCmWoTv9KHb1KbVNPWhmssvJ6TTHAW69kvHLR02mlgSZ2IkakV2LWjVGzud+sXPtxiV69Vk7hgWXUzBKddhlH/GWQ5OS5daFBZ7GvAkg8ubQ3e2soO56DYk=,iv:yya9DjK3oD6Xvt9CgF74JhE86cdeNqcJvaTfb5Bw4m8=,tag:Rw2AKHIUSr5rykoExV5Rqw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.1
