cloudflare_api_token: ENC[AES256_GCM,data:oMIiHWXW6bPmPZucJXngfz+F29mXwLiU1ppHMFwmfV9ekoDGcx19CA==,iv:WSyTh7+zDnrEiPm8bkjq7tbs5lU3p18DSHdOtAMs4wg=,tag:CIJ45UD6Pk56bObuJ9eDhA==,type:str]
cloudflare_zone_id: ENC[AES256_GCM,data:Vn4H3OsFTIEgfK4xR1x4nv0ZW8xRZ1aOGHm9ptEbEz8=,iv:BJFeE89q20T6ISS8JwVpwL6uVfVnEC+SRYC6CPUH4Vw=,tag:JevXVDOpijTSNlTt4Bx23g==,type:str]
nordvpn_wireguard_private_key: ENC[AES256_GCM,data:zz+wEYPM3W7R7rJRYY1vKUfrnIVQu2ZG0Ozk2RuuJXKd3sLHl/sumy24C80=,iv:Si8ksz6+Y1b4vgkQXk0G+KldkpdqCzKeCiocrQZs3gc=,tag:Rt2rS96CzH1EPbJvqETwxw==,type:str]
proxmox_api_token: ENC[AES256_GCM,data:wP1Ck+J+gGsejs5rQSHML+7wjqmN5TY8YkRWx8wvhtqRsH3UX0s9T7dSoY9d9MFKOY92Q80uQ7YLtA==,iv:52I5kgT+GQ0+QCeOg0g43vFuj/mkn/B7jH5f7a3d9UQ=,tag:AUf/kElJGRVJeYaebhydJQ==,type:str]
vps_public_ip: ENC[AES256_GCM,data:KntVRn9mUYKx/z545A==,iv:2ur6nV1yB6HWpc8nk4o18deMrkmaDHSMkp2VS/20tA4=,tag:3+GutPaxat+Gm7beTAXdeQ==,type:str]
acme_email: ENC[AES256_GCM,data:Oyya0HFXtfD0wWSXPDCoMJMPt2o1eQ==,iv:dmZ5QZ4nnY1rYHTyzi9aocyLxzTJO6Mn3ZPfKkyIsm8=,tag:Y+81OsC5sTwAOBGDVr+6ow==,type:str]
ha_latitude: ENC[AES256_GCM,data:ew1aysKGqpPc,iv:GAKOREdTUbY7iMRmD9Xl4SxWZlnMJ5fQ1t9RzXsXOGc=,tag:me+MGFFcrEFGXSlk8yIpLQ==,type:float]
ha_longitude: ENC[AES256_GCM,data:bbwvEpWnlfFP,iv:BWELpT8JaaQm15OWYwb+m/KHV7/2NMTkwf7u3FYsbO4=,tag:CbVD7Q2FySxzFKZueEkKpw==,type:float]
ha_elevation: ENC[AES256_GCM,data:HK68bbQ=,iv:CLLs7nQCjZTI8wHLa/EyORk9ki07fq/o1CU1jnTqyaQ=,tag:sSfFF/KZG5oi5a2WTFApEg==,type:float]
authentik_admin_username: ENC[AES256_GCM,data:Q7++oWjQZg==,iv:1wiZ1Hb9YuNvEu2Gm4gFFf3IIE+B0eVmjBGRtXFhNis=,tag:pW1JLTlJaSdn4Zaygq2Odw==,type:str]
mikrotik_admin_password: ENC[AES256_GCM,data:uDRjk22FIad/jcewTH4=,iv:NYAAMar+T9/XPYCEiYgFoa703GR72WAg9Mobkb96DCk=,tag:J25IxfJKCivel5Zn44Ejsw==,type:str]
anysub_hf_token: ENC[AES256_GCM,data:3z+BiTzEDEvUIC5iIYACes8Ki9L3FHIk95XM1lTgmi7rtF5JIw==,iv:Akl+wvRxuT0/RA/B/c/Q9jiz8l3aBFRnA0CH7YNRzSs=,tag:8iA7WmNX94l2Jnvn5SlP9Q==,type:str]
sops:
    age:
        - recipient: age18nas3jz5knygax063tjeek855fx69jc3ycn9kzn9qxpdnhe3957s8dz9ky
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMMm42Q0poakdnS2FmR3Az
            TWQrS0tDWnpuRTFYZkM0M05GWmt6ck1yV2x3Ck9ORDdHbVQ3TVJrcFZ5MWJnUU9W
            RTBiSjFrNXczK2ZRejFtc2d4clo5WGMKLS0tIGhJTFppSkkvWnprWHR5anliQW1P
            YVlEbE9uMDNtdkNxWEdreHF0WVUyUW8KvV9RmRZ0bRK5q0VuUAel8PmhruR9D5ce
            No/0kZKVbgNvtR0gFy6FpwSFkNIAcF/dDk4/2FSD2aiLaBqBz59jag==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1rxyzhqxykdrx9rt504dxjd0hch3aysxs0dzrsnfadc4ur59q537s7w873e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6VHgrMHRYWUpscUhBS3g3
            cHFjVktxTDJkRTVDaFBVZGMrRFBLa0pLY1ZVCkpTWk12a1hEbzVpWU5LUHBNY2hS
            SFlqRmwvZHA3M25NOGdKOUhQYVNlM1UKLS0tICttVXAwWkpXd25mQkF3dXRSUU4y
            eVdad3NtZTNHV1NpRVVXNGg5TWlxRTQK4BIcro6bzCvp3M8XXKaMGDA/oWKTEkRs
            Ox5xkOMdDPt4rbpXO1SLE2YsrOz1ukyno3N5IOriRLkZfooI5KH2tw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1rxyzhqxykdrx9rt504dxjd0hch3aysxs0dzrsnfadc4ur59q537s7w873e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFU0hpNE5zWW1VYTl5Q1F0
            a3ovTERseVJjakY2SERQU1NpS2p2L2F6U1YwCm9CNGNybkEzd0pUSm1odTlVVEFY
            ZURJTWp4eUFTeXNob1lGbnVYRzg2aUEKLS0tIG9zbVFjOFdOdlh0UURJNTJHYjcx
            UE9FdGIxTU0vKzBWdEw2eGw5d01HVk0KZQZD4vsmgia6nWz1eO76//uJ9GD/+0Ij
            XDL1CAqzfy0N5oE4yNfxmABrFvwwVqDtT5FH23dnpviNIkTwuc3pKw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T10:47:16Z"
    mac: ENC[AES256_GCM,data:ta3FC/BraJTMzLYuj4fNSipUUGfbj4wMDUwbJkg8gdgdLwO7e1+eKhQ/sIXb/mYLoY3rnOj0zr1uygicF4/JU4baivbI8q5qGt2DIi6CiFfzM2JIjSmmumfXDBlO5TeHsbHvnTZavPTRCbG3qXy720aZWUfvVLY3qRyA181n47s=,iv:dV068N0pcPoW7fZXd/jkRMfRIBHkCET7ciTPoa75XmY=,tag:YAu/fKHiMZB7tSCnAfjFtg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
