cloudflare_api_token: ENC[AES256_GCM,data:tTj9Jkwr6wM+ZZy+k0ZqNnCXxKjWqQ8lgxoEpQtPl1nntAkEuBvwVw==,iv:WSyTh7+zDnrEiPm8bkjq7tbs5lU3p18DSHdOtAMs4wg=,tag:c7JtUfCXAOFp++HgkvxEcg==,type:str]
cloudflare_zone_id: ENC[AES256_GCM,data:cOLXrrJXIbvoYcR4eHeEjzIShA1SIRHg8l5V+MSxU+w=,iv:BJFeE89q20T6ISS8JwVpwL6uVfVnEC+SRYC6CPUH4Vw=,tag:rNjCZWQDdKu00KEBFlFyUQ==,type:str]
nordvpn_wireguard_private_key: ENC[AES256_GCM,data:HSuocsS75uiYyxkOHWXLPFwxyXoH0OPvFkSHYOAk/KHXlTz7O9cHjsQbSfc=,iv:Si8ksz6+Y1b4vgkQXk0G+KldkpdqCzKeCiocrQZs3gc=,tag:4ODFCv4TQDkXgz3R9KtA2g==,type:str]
proxmox_api_token: ENC[AES256_GCM,data:Of1pq8hEmGOlnDcpUTD7uMMfRTbUtiOXdmrZl4PxxFIzP+0kIOHBlMrgsGCD/fwgN3ZjrA2oktMZ1w==,iv:52I5kgT+GQ0+QCeOg0g43vFuj/mkn/B7jH5f7a3d9UQ=,tag:J047U65+JzIJDQ06iBoryQ==,type:str]
vps_public_ip: ENC[AES256_GCM,data:v+wtO6Hwb7vrNKDivg==,iv:2ur6nV1yB6HWpc8nk4o18deMrkmaDHSMkp2VS/20tA4=,tag:7gzCf+VxlHZ7CYy/1+FSOw==,type:str]
acme_email: ENC[AES256_GCM,data:JjvuyzEqAhSDKf5Xsm1YNgeuWnLwsA==,iv:dmZ5QZ4nnY1rYHTyzi9aocyLxzTJO6Mn3ZPfKkyIsm8=,tag:n+JfwEObPFSvuSDemOeAXg==,type:str]
ha_latitude: ENC[AES256_GCM,data:kDS6+6h6b/Iu,iv:GAKOREdTUbY7iMRmD9Xl4SxWZlnMJ5fQ1t9RzXsXOGc=,tag:VeQlwlqdLXJpYm7IokRGuQ==,type:float]
ha_longitude: ENC[AES256_GCM,data:uUdItYIq0kzl,iv:BWELpT8JaaQm15OWYwb+m/KHV7/2NMTkwf7u3FYsbO4=,tag:lO8U7Es43gCGezy1qdN5Fw==,type:float]
ha_elevation: ENC[AES256_GCM,data:q7nHuBA=,iv:CLLs7nQCjZTI8wHLa/EyORk9ki07fq/o1CU1jnTqyaQ=,tag:hNsGbBGji30tXtWbUaEOxA==,type:float]
authentik_admin_username: ENC[AES256_GCM,data:lPdxTJoDLw==,iv:1wiZ1Hb9YuNvEu2Gm4gFFf3IIE+B0eVmjBGRtXFhNis=,tag:wz19JOplOrPuvwUHV742yw==,type:str]
sops:
    age:
        - recipient: age18nas3jz5knygax063tjeek855fx69jc3ycn9kzn9qxpdnhe3957s8dz9ky
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWd3VHTkNVdnR5d0lGYm5Q
            UExBKzB4bzBiZi9yMVVxbWpUQU0yaTIwOEFBClNCL0JZVUcrd2xXV0R0Zk5pOG1z
            N3FBd0tVdEQxV0twSklzYVFpZk5ScmcKLS0tIHRuR3hPZlhMOTE1WDRMRVFVODNJ
            VDVzNzdub2RibHlXYm4xTkFBV2xXZk0KWP9trbo4GOEsDt+NugFjY8EdaFWoD/vZ
            qBxHJEOnW2m9Mour9b3N7PNeZ8vP9Nq7RnKfY36kpaURRhk9NSEhiw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-17T08:23:27Z"
    mac: ENC[AES256_GCM,data:5PEMbuRav8BP0mGy7u5VnacWCwny3hi9EbRAyH9K5RzrDyskCqaEQPkNCuBA3xSvE1WGQ7XerS09Wcx8GDjP1RpJcosKxUhsMcGyaXy+vAVnOMGaikYUr9e+MnaFIzHBXB1NlCEz1FuzBPpOFH3bPszwzwzkH8bo60X/w3To9so=,iv:CvGHZIKbtwSVatBetnnh3gJDr7A+OCLIVrxi3ZMnFsY=,tag:BjHliho699wu0h1UHkK2+A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.1
