---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ha-configuration
  namespace: home-assistant
  labels:
    app.kubernetes.io/name: home-assistant
    app.kubernetes.io/instance: home-assistant
data:
  configuration.yaml: |
    homeassistant:
      name: Home
      latitude: !secret ha_latitude
      longitude: !secret ha_longitude
      elevation: !secret ha_elevation
      currency: EUR
      country: IT
      unit_system: metric
      time_zone: Europe/Rome

    default_config:

    openid:
      client_id: !secret ha_oidc_client_id
      client_secret: !secret ha_oidc_client_secret
      configure_url: "https://auth.{{ .Values.domain }}/application/o/home-assistant/.well-known/openid-configuration"
      scope: "openid profile email"
      username_field: preferred_username
      create_user: true

    http:
      use_x_forwarded_for: true
      trusted_proxies:
        - 10.0.0.0/16
        - 10.96.0.0/12
