---
- name: Check Bottega enabled RouterOS services
  community.routeros.command:
    commands:
      - /ip service print terse where name={{ item }}
  loop: "{{ bottega_mikrotik_enabled_services }}"
  register: _bottega_enabled_services
  changed_when: false

- name: Limit Bottega RouterOS services to the management subnets
  community.routeros.command:
    commands:
      - >-
        /ip service set [find where name="{{ item.item }}"]
        disabled=no
        address={{ bottega_mikrotik_management_subnets | join(',') }}
  loop: "{{ _bottega_enabled_services.results }}"
  loop_control:
    label: "{{ item.item }}"
  vars:
    _current_subnets: >-
      {{ (item.stdout[0] | regex_search('address=([^\s]*)', '\1')
      | first | default('')).split(',') | reject('equalto', '') | list }}
  when: >-
    (item.stdout[0] is search('(^|\\s)X\\s+name=')) or
    ((_current_subnets |
    symmetric_difference(bottega_mikrotik_management_subnets) |
    length) > 0)

- name: Check Bottega disabled RouterOS services
  community.routeros.command:
    commands:
      - /ip service print terse where name={{ item }}
  loop: "{{ bottega_mikrotik_disabled_services }}"
  register: _bottega_disabled_services
  changed_when: false

- name: Disable unused Bottega RouterOS services
  community.routeros.command:
    commands:
      - /ip service set [find where name="{{ item.item }}"] disabled=yes
  loop: "{{ _bottega_disabled_services.results }}"
  loop_control:
    label: "{{ item.item }}"
  when: "item.stdout[0] is not search('(^|\\s)X\\s+name=')"

- name: Check optional Bottega disabled RouterOS services
  community.routeros.command:
    commands:
      - /ip service print terse where name={{ item }}
  loop: "{{ bottega_mikrotik_optional_disabled_services }}"
  register: _bottega_optional_disabled_services
  changed_when: false

- name: Disable optional Bottega RouterOS services when present
  community.routeros.command:
    commands:
      - /ip service set [find where name="{{ item.item }}"] disabled=yes
  loop: "{{ _bottega_optional_disabled_services.results }}"
  loop_control:
    label: "{{ item.item }}"
  when:
    - "'name=' ~ item.item in item.stdout[0]"
    - "item.stdout[0] is not search('(^|\\s)X\\s+name=')"
